#Regras fixas da logica do jogo

#Definindo vida e os bonus de vida do Herói
VIDA_INICIAL_HEROI = 5
BONUS_VIDA_APOS_VITORIA = 5

#Pausas de textos
PAUSA_NARRACAO = 1.6
PAUSA_DIALOGO = 1.4
PAUSA_BATALHA = 0.9

#Vida e numeros sorteados por monstro no turno
VIDA_ANTI_AUTHORIZATUS = 4
DADOS_ANTI_AUTHORIZATUS = 1

VIDA_GLOZIUM_ADMINISTRATUS = 6
DADOS_GLOZIUM_ADMINISTRATUS = 2

VIDA_WORM = 12
DADOS_WORM = 3

VIDA_SANDUBINHA_REVERSE = 30
DADOS_SANDUBINHA_REVERSE = 8

VIDA_GARGULAS_CAPTCHAS = 10
VIDA_GLOZIUM = 100
DADOS_GLOZIUM = 10
